version: '3'

services:
  web:
      environment:
          - DB_NAME=postgres
          - DB_USER=postgres
          - DB_PASSWORD=password
          - DB_HOST=db  
          - DB_PORT=5432
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - 8000:8000
      depends_on:
        - db
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    
